### ISSUE TITLE
Collect a list of services

### ISSUE THREAD

**Issue by sampov2** [spatineo/geoe3-quality-dashboard#1]
We need to produce a list of services in GeoE3. For each service we need:
- URL to the service API
- URL to dataset metadata
- Possibly a URL to service metadata
- Generate an ID for each service (can be anything)

The list should be added as a file in the repository. File type choice is up to you

**Comment by ccossec** [comment]
A list of services has been uploaded to the repository (branch : GeoE3-services).

The information summarized in the list is from [the GeoE3 website](https://vm3897.kaj.pouta.csc.fi/geoe3/contents/) and a [google sheet](https://docs.google.com/spreadsheets/d/1QI4ktMieZHSBXEmPtYM1gg8sS-mLpiUApvq_ltBLq68/edit#gid=841376915) related to the project.

Amongst the services currently linked to the platform, some URLs to dataset metadata are missing (**if necessary, I can look further into those**).
