### ISSUE TITLE
Implement a first draft of the service evaluator

### ISSUE THREAD

**Issue by sampov2** [spatineo/geoe3-quality-dashboard#2]
Implement the first draft of the service evaluator that should:

1. Read the service listing
2. Read the evaluator configuration (from a JSON file or database, specifics are up to you) - at this time the contents should be minimal: write just a few metrics 
3. Produce values for each metric
4. Produce scores for each metric/measure/quality element/dimension/viewpoint
5. Write output to file format usable with Power BI

Language: python (3.x)

**Comment by ccossec** [comment]
Implementation of the first viewpoint (service and dataset) is complete.
1. Service listing is read
2. Evaluator configuration (from a JSON file) complete for the first viewpoint
3. Value for each metric is extracted from metadata, API or CSV file
4. Score for each metric/measure/quality element/dimension/viewpoint is produced
5. Output to CSV usable in Power BI (output could easily be a DataFrame that can be imported in Power BI through a Python script, maybe in the future)
